const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slin Shirt",
      category: "Shirt",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quility product",
    },
    {
      _id: "2",
      name: "Lacoste Slin Shirt",
      category: "Shirt",
      image: "/images/p2.jpg",
      price: 120,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quility product",
    },
    {
      _id: "3",
      name: "Nike Slin Shirt",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 120,
      brand: "Nike",
      rating: 3,
      numReviews: 10,
      description: "high quility product",
    },
    {
      _id: "4",
      name: "Nike Slin pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      brand: "Nike",
      rating: 4.5,
      numReviews: 40,
      description: "high quility product",
    },
    {
      _id: "5",
      name: "Puma Slin Shirt",
      category: "Shirt",
      image: "/images/p5.jpg",
      price: 120,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quility product",
    },
    {
      _id: "6",
      name: "Adidas Slin pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quility product",
    },
  ],
};

export default data;
